### ISSUE TITLE
v1.0.0 throws "z is not a function"

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-core#146]
Marp Core v1.0.0 throws `TypeError: z is not a function` just by calling `require('@marp-team/marp-core')`.

```
> require('@marp-team/marp-core')
Thrown:
TypeError: z is not a function
    at Object.<anonymous> (/Users/yhatt/Programs/marp-team/marp-cli/node_modules/@marp-team/marp-core/lib/marp.js:1:941)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

The same issue has reported in https://github.com/marp-team/marp-cli/pull/198 and https://github.com/marp-team/marp-react/issues/19.

**Comment by yhatt** [comment]
### Unpacked source

```js
var plugin = createCommonjsModule(function (module, exports) {

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

/** @module */

/**
 * Create Marpit plugin.
 *
 * Generate Marpit plugin from passed markdown-it plugin. Marpit plugin needs
 * markdown-it instance with `marpit` member.
 *
 * @alias module:plugin
 * @param {Function} plugin Base plugin for markdown-it.
 * @returns {Function} Generated Marpit plugin.
 */
function marpitPlugin(plugin) {
  // eslint-disable-next-line func-names
  return function (md, ...args) {
    if (md.marpit) return plugin.call(this, md, ...args);
    throw new Error('Marpit plugin has detected incompatible markdown-it instance.');
  };
}

var _default = marpitPlugin;
exports.default = _default;
});

unwrapExports(plugin);

var plugin$1 = plugin;
```

```
Thrown:
TypeError: plugin$1 is not a function
    at Object.<anonymous> (/Users/yhatt/Programs/marp-team/marp-core/lib/marp.js:70:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

I'm sure it has related to https://github.com/rollup/plugins/issues/102.
